// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/insurance-variants/ClinicalSplit.tsx": () => import("../components/mockups/insurance-variants/ClinicalSplit.tsx"),
  "./components/mockups/insurance-variants/DataStudio.tsx": () => import("../components/mockups/insurance-variants/DataStudio.tsx"),
  "./components/mockups/insurance-variants/HealthcarePortal.tsx": () => import("../components/mockups/insurance-variants/HealthcarePortal.tsx")
};
